const DEEP_DOCS_CONTEXT = {
    "product_entities": [
        "Abbot",
        "Abbott",
        "Abbreviations",
        "Abijith",
        "Ability",
        "Abnormal",
        "About",
        "About Audience Group Filters",
        "About Capillary",
        "About Kafka\n\nKafka",
        "About Promo Codes",
        "About User Group Loyalty",
        "Above",
        "Absolute",
        "Absolute Value",
        "Absolutely",
        "Abuse",
        "Academy",
        "Academy Certificates",
        "Accelerate",
        "Accept Preview",
        "Acceptable",
        "Accepted",
        "Accepts",
        "Access",
        "Access Configuration Admin",
        "Access Configuration Viewer",
        "Access Control",
        "Access Control Team",
        "Access Credit Management Console\n\nTo",
        "Access Group",
        "Access Key",
        "Access Libraries",
        "Access Management",
        "Access Neo Portal\n\nYou",
        "Access Power",
        "Access Report",
        "Access Requirements",
        "Access Roles",
        "Access Roles\n\nAccessing Vulcan",
        "Access Sensitive Data",
        "Access Settings",
        "Access Team",
        "Access Token",
        "Access Tokens",
        "Accessibility",
        "Accessibility Needs",
        "Accessible",
        "Accessible Entities",
        "Accessing",
        "Accessing Aira Coder\n\nYou",
        "Accessing App Request Logs\n\nTo",
        "Accessing Capillary",
        "Accessing Configuration Manager",
        "Accessing Connect",
        "Accessing Dev Console\n\nTo",
        "Accessing Engage",
        "Accessing Neo\n\n\nYou",
        "Accessing Platform Metrics\n\nTo",
        "Accessing Vulcan",
        "Accessory",
        "Accessory Bundle Deal",
        "Accommodate Special Circumstances",
        "According",
        "Accordingly",
        "Account",
        "Account\n\nYou",
        "Account Configuration",
        "Account Configuration\n\nThe",
        "Account Id",
        "Account Link Policy",
        "Account Linking Identifier",
        "Account Manager",
        "Account Merge",
        "Account Merge Change Request",
        "Account Merge Configuration",
        "Account Merge Requests\n\nYou",
        "Account Merge Settings",
        "Account Name",
        "Account Updates",
        "Accounts",
        "Accrual",
        "Accrue",
        "Accumulate",
        "Accuracy",
        "Accurate",
        "Achieve",
        "Achieved",
        "Achieved Value",
        "Achieved Value Above Defined Target",
        "Achievement",
        "Achyuthanandan",
        "Acquire",
        "Acquire Distributed Lock",
        "Acquisition",
        "Acronym",
        "Across",
        "Across Customer Limit",
        "Across Member Limits",
        "Across Org",
        "Action",
        "Action Blocks",
        "Action Building Block",
        "Action Building Blocks",
        "Action Link",
        "Action Logs",
        "Action Name",
        "Action Object",
        "Action Objects",
        "Action Origin",
        "Action Settings",
        "Action Type",
        "Action Types",
        "Actionable",
        "Actions",
        "Activate",
        "Activate\n\nThis",
        "Activate Badge",
        "Activate Cart Promotion",
        "Activate Engage",
        "Activate Member Care",
        "Activate Program",
        "Activate Promotion",
        "Activate Promotions",
        "Activated",
        "Activates",
        "Activating",
        "Activating Badges",
        "Activation",
        "Activation Date",
        "Activation Status",
        "Activation String",
        "Active",
        "Active Adobe Experience Platform",
        "Active Badge Scenarios",
        "Active Campaigns",
        "Active Capillary",
        "Active Coupon",
        "Active Coupons",
        "Active Customers",
        "Active Segments\n\n              Inactive",
        "Active Sharingan",
        "Active State",
        "Active Status",
        "Active Stores",
        "Actively",
        "Activities",
        "Activity",
        "Activity\n\nThis",
        "Activity Attribute"
    ],
    "featured_terms": [
        "\n\n## ",
        "\n\n## Attribute value\n\nAn ",
        "\n\n## Brand\n\nA ",
        "\n\n## Category\n\nA ",
        "\n\n## REQ 02: Onboarding\n\n",
        "\n\n## Tracker API\n\nConfigure ",
        "\n\n### ",
        "\n\n### Disable\n\n1. Disable ",
        "\n\n### Disable\n\n1. Set ",
        "\n\n### Email OTP\n\n1. Enable ",
        "\n\n### Ledger Explode APIs\n\n",
        "\n\n#### ",
        "\n\n1. ",
        "\n\n2. ",
        "\n\n3. ",
        "\n\n4. ",
        "\n\n<br />\n\n",
        "\n\nClick ",
        "\n        ",
        "\n   Marketing \u2192 ",
        "\n   OTP \u2192 ",
        "                        | ",
        "                    | ",
        "                   | ",
        "                  | ",
        "              | A ",
        "            | ",
        "           | A ",
        "    | ",
        " (10 off 100) and ",
        " (the trigger) and the ",
        " -> =,\\<=,>=,>,\\<\\\n",
        " -> BigDecimal\\\n",
        " 2. row ",
        " : NA\\\n",
        " : currentCustomer\\\n",
        " >,\\<,>=,\\<=,==\\\n",
        " >,\\<,>=,\\<=,=\\\n",
        " BigDecimal\n\n",
        " BigDecimal\\\n",
        " Boolean\\\n",
        " Channel configurations",
        " Conglomerate\n\n",
        " Description\\\n",
        " Email\\\n",
        " Engage+",
        " Example:",
        " From the ",
        " Insights",
        " Int (Integer)\\\n",
        " Mandatory Parameters ",
        " Mandatory parameters ",
        " NA\\\n",
        " Next",
        " Non Mandatory Parameters ",
        " Non mandatory parameters ",
        " Not Null",
        " Retail\n\n",
        " String\\\n",
        " Value\\\n",
        " Values ",
        " Values allowed ",
        " \\<,>,>=,\\<=,==\\\n",
        " and ",
        " and a ",
        " avgSpendPerVisit\\\n",
        " current customer\\\n",
        " currentCustomer()\\\n",
        " currentCustomer\\\n",
        " customFieldValueExcludes ",
        " dd.mm.yy",
        " during Enrolment. |\n| ",
        " field. The ",
        " firstName\\\n",
        " hasWeChatProfile\\\n",
        " initialCurrentPoints\\\n",
        " int\\\n",
        " integer\\\n",
        " is mandatory.\n\n| ",
        " is set to "
    ],
    "us_standard": {
        "behaviour": "behavior",
        "analyse": "analyze",
        "programme": "program",
        "organisation": "organization",
        "enrol": "enroll",
        "enrolment": "enrollment",
        "catalogue": "catalog",
        "centre": "center",
        "colour": "color",
        "customisation": "customization",
        "customise": "customize",
        "authorised": "authorized",
        "cancelled": "canceled",
        "standardisation": "standardization"
    },
    "style_guide": {
        "core_principles": [
            "Clarity",
            "Conciseness",
            "Consistency",
            "User-Centeredness",
            "Actionability"
        ],
        "terminology": {
            "plain_language": "Use simple, everyday language.",
            "avoid_jargon": "Minimize technical or industry-specific terms.",
            "positive": "Frame copy helpfully, focusing on solutions."
        },
        "tone": "Professional, respectful, empathetic, conversational but not overly casual.",
        "examples": [
            {
                "bad": "Reward member on the activities/engagements",
                "good": "Reward members for completing specific actions, like a purchase or a profile update"
            },
            {
                "bad": "Select the program name the promotion is part of",
                "good": "Select the loyalty program to link to the loyalty promotion"
            },
            {
                "bad": "Customers to be enrolled for promotion",
                "good": "Choose your audience"
            }
        ]
    },
    "voice": "Professional, respectful, empathetic, conversational within reason, and brand-specific."
};
if (typeof module !== 'undefined') module.exports = DEEP_DOCS_CONTEXT;